import {
  inspectGeneratedFile,
  normalize,
  sha256,
  upsertManagedBlock,
  type GeneratedFile,
} from "@engineering-skills/adapters";

export type WriteAction = "create" | "update" | "unchanged" | "conflict";

export interface PlannedWrite {
  /** Project-relative path. */
  readonly path: string;
  /** The complete file text to write. */
  readonly content: string;
  readonly action: WriteAction;
  readonly reason: string;
  /** Hash of what we own in this file: the whole file, or the managed block's content. */
  readonly hash: string;
}

/** Reads a project-relative file; undefined when it does not exist. */
export type Reader = (path: string) => Promise<string | undefined>;

/**
 * Decide what writing one generated file would do, without writing it.
 * Hand-edited generated files, files that were never generated, and hand-edited managed blocks
 * are conflicts: they stop generation unless `force` says to replace them.
 */
export async function planFile(
  file: GeneratedFile,
  read: Reader,
  options: { readonly force: boolean },
): Promise<PlannedWrite> {
  const existing = await read(file.path);

  if (file.marker === "block") {
    const result = upsertManagedBlock(existing, file.blockId as string, file.content, {
      force: options.force,
    });
    const hash = sha256(normalize(file.content));
    const reasons = {
      created: "new file",
      inserted: "adds the managed block to your existing file; the rest is untouched",
      updated: "the managed block changed",
      unchanged: "up to date",
      conflict: "the managed block was edited by hand",
    } as const;
    const action: WriteAction =
      result.status === "created"
        ? "create"
        : result.status === "unchanged"
          ? "unchanged"
          : result.status === "conflict"
            ? "conflict"
            : "update";
    return { path: file.path, content: result.text, action, reason: reasons[result.status], hash };
  }

  const hash = sha256(file.content);
  if (existing === undefined)
    return { path: file.path, content: file.content, action: "create", reason: "new file", hash };

  const state = inspectGeneratedFile(existing);
  if (state !== "pristine" && !options.force) {
    return {
      path: file.path,
      content: existing,
      action: "conflict",
      reason:
        state === "edited"
          ? "generated file was edited by hand"
          : "exists and was not generated by Engineering Skills",
      hash,
    };
  }
  if (state === "pristine" && normalize(existing) === file.content) {
    return {
      path: file.path,
      content: file.content,
      action: "unchanged",
      reason: "up to date",
      hash,
    };
  }
  return {
    path: file.path,
    content: file.content,
    action: "update",
    reason: state === "pristine" ? "content changed" : "replaces your version (--force)",
    hash,
  };
}

export const planFiles = async (
  files: readonly GeneratedFile[],
  read: Reader,
  options: { readonly force: boolean },
): Promise<PlannedWrite[]> => Promise.all(files.map((f) => planFile(f, read, options)));
