import {
  renderGeneratedFile,
  upsertManagedBlock,
  type GeneratedFile,
} from "@engineering-skills/adapters";
import { describe, expect, it } from "vitest";
import { planFile, type Reader } from "./plan.js";

const META = { version: "1", source: "c" };
const full = (body: string): GeneratedFile => ({
  path: "out.md",
  content: renderGeneratedFile({ body }, META),
  marker: "full",
});
const block = (content: string): GeneratedFile => ({
  path: "CLAUDE.md",
  content,
  marker: "block",
  blockId: "es",
});
const files =
  (map: Record<string, string>): Reader =>
  async (p) =>
    map[p];
const OFF = { force: false };

describe("planFile: whole generated files", () => {
  it("creates a new file", async () => {
    expect(await planFile(full("A"), files({}), OFF)).toMatchObject({
      action: "create",
      reason: "new file",
    });
  });

  it("is unchanged when the file is pristine and identical", async () => {
    const f = full("alpha");
    expect(await planFile(f, files({ "out.md": f.content }), OFF)).toMatchObject({
      action: "unchanged",
    });
  });

  it("updates a pristine file whose content changed", async () => {
    const old = full("alpha");
    expect(await planFile(full("beta"), files({ "out.md": old.content }), OFF)).toMatchObject({
      action: "update",
      reason: "content changed",
    });
  });

  it("stops at a hand-edited generated file, and replaces it only when forced", async () => {
    const edited = full("alpha").content.replace("alpha", "alpha edited");
    expect(await planFile(full("beta"), files({ "out.md": edited }), OFF)).toMatchObject({
      action: "conflict",
      reason: "generated file was edited by hand",
      content: edited,
    });
    expect(
      await planFile(full("beta"), files({ "out.md": edited }), { force: true }),
    ).toMatchObject({
      action: "update",
      reason: "replaces your version (--force)",
    });
  });

  it("never overwrites a file it did not generate", async () => {
    const mine = "# My own INSTRUCTIONS\n";
    expect(await planFile(full("B"), files({ "out.md": mine }), OFF)).toMatchObject({
      action: "conflict",
      reason: "exists and was not generated by Engineering Skills",
    });
  });

  it("does not treat an editor's CRLF conversion as an edit", async () => {
    const f = full("alpha");
    expect(
      await planFile(f, files({ "out.md": f.content.replace(/\n/g, "\r\n") }), OFF),
    ).toMatchObject({ action: "unchanged" });
  });
});

describe("planFile: managed blocks in a file the team owns", () => {
  it("creates the file when it does not exist", async () => {
    expect(await planFile(block("Rules"), files({}), OFF)).toMatchObject({ action: "create" });
  });

  it("inserts the block and keeps the team's text exactly", async () => {
    const mine = "# Team notes\n\nUse tabs.\n";
    const plan = await planFile(block("Rules"), files({ "CLAUDE.md": mine }), OFF);
    expect(plan.action).toBe("update");
    expect(plan.reason).toContain("the rest is untouched");
    expect(plan.content.startsWith(mine)).toBe(true);
  });

  it("is unchanged when the block is current", async () => {
    const current = upsertManagedBlock("# T\n", "es", "Rules").text;
    expect(await planFile(block("Rules"), files({ "CLAUDE.md": current }), OFF)).toMatchObject({
      action: "unchanged",
    });
  });

  it("updates the block when the rules changed", async () => {
    const current = upsertManagedBlock("# T\n", "es", "Old").text;
    expect(await planFile(block("New"), files({ "CLAUDE.md": current }), OFF)).toMatchObject({
      action: "update",
      reason: "the managed block changed",
    });
  });

  it("stops at a hand-edited block, and replaces it only when forced", async () => {
    const edited = upsertManagedBlock("# T\n", "es", "Old").text.replace("Old", "Mine");
    expect(await planFile(block("New"), files({ "CLAUDE.md": edited }), OFF)).toMatchObject({
      action: "conflict",
      content: edited,
    });
    const forced = await planFile(block("New"), files({ "CLAUDE.md": edited }), { force: true });
    expect(forced.action).toBe("update");
    expect(forced.content).toContain("New");
    expect(forced.content.startsWith("# T\n")).toBe(true);
  });

  it("records the hash of what the block owns, not of the whole file", async () => {
    const a = await planFile(block("Rules"), files({ "CLAUDE.md": "# one\n" }), OFF);
    const b = await planFile(
      block("Rules"),
      files({ "CLAUDE.md": "# something else entirely\n" }),
      OFF,
    );
    expect(a.hash).toBe(b.hash);
  });
});
