import type { CanonicalOutput } from "@engineering-skills/core";
import { describe, expect, it } from "vitest";
import {
  ADAPTERS,
  claudeAdapter,
  codexAdapter,
  genericAdapter,
  getAdapter,
  inspectGeneratedFile,
  renderAdapter,
  upsertManagedBlock,
  type AiAdapter,
} from "./index.js";
import { OPTIONS, existingLayered } from "./sample-output.js";

const opts = (mode: "inline" | "reference") => ({ ...OPTIONS, mode });

describe("registry", () => {
  it("offers claude, codex and generic", () => {
    expect(Object.keys(ADAPTERS).sort()).toEqual(["claude", "codex", "generic"]);
    expect(getAdapter("claude")).toBe(claudeAdapter);
    expect(getAdapter("nope")).toBeUndefined();
  });
});

describe("generic", () => {
  it("writes one self-contained generated file", async () => {
    const [file, ...rest] = renderAdapter(genericAdapter, existingLayered(), opts("inline"));
    expect(rest).toEqual([]);
    expect(file?.path).toBe(".engineering/generated/INSTRUCTIONS.md");
    expect(file?.marker).toBe("full");
    expect(inspectGeneratedFile(file?.content ?? "")).toBe("pristine");
    await expect(file?.content).toMatchFileSnapshot("./__snapshots__/generic-existing-layered.md");
  });
});

describe("codex", () => {
  it("puts the rules in a managed block of AGENTS.md", async () => {
    const [file] = renderAdapter(codexAdapter, existingLayered(), opts("inline"));
    expect(file).toMatchObject({
      path: "AGENTS.md",
      marker: "block",
      blockId: "engineering-skills",
    });
    await expect(file?.content).toMatchFileSnapshot("./__snapshots__/codex-existing-layered.md");
  });
});

describe("claude", () => {
  it("inline: everything in the CLAUDE.md block", () => {
    const files = renderAdapter(claudeAdapter, existingLayered(), opts("inline"));
    expect(files).toHaveLength(1);
    expect(files[0]).toMatchObject({ path: "CLAUDE.md", marker: "block" });
    expect(files[0]?.content).toContain("## Clean Code");
  });

  it("reference: facts in CLAUDE.md, each skill in its own .claude/skills file", async () => {
    const files = renderAdapter(claudeAdapter, existingLayered(), opts("reference"));
    expect(files.map((f) => f.path)).toEqual([
      "CLAUDE.md",
      ".claude/skills/eng-core-project-onboarding/SKILL.md",
      ".claude/skills/eng-quality-clean-code/SKILL.md",
    ]);
    const [entry, onboarding] = files;
    expect(entry?.content).toContain("## Project context");
    expect(entry?.content).toContain(
      "`eng-quality-clean-code` — Clean Code: Naming, function and module rules.",
    );
    expect(entry?.content).not.toContain("Read the nearest module before writing.");
    expect(
      onboarding?.content.startsWith(
        '---\nname: eng-core-project-onboarding\ndescription: "Learn an existing repository before changing it. Part of this project\'s engineering rules (generated)."\n---\n<!-- GENERATED BY',
      ),
    ).toBe(true);
    expect(inspectGeneratedFile(onboarding?.content ?? "")).toBe("pristine");
    await expect(entry?.content).toMatchFileSnapshot("./__snapshots__/claude-reference-entry.md");
  });

  it("honours an output path override", () => {
    const files = renderAdapter(claudeAdapter, existingLayered(), {
      ...opts("inline"),
      outputPath: "docs/CLAUDE.md",
    });
    expect(files[0]?.path).toBe("docs/CLAUDE.md");
  });
});

describe("what every adapter tells the agent first", () => {
  const output = existingLayered();
  const text = renderAdapter(genericAdapter, output, opts("inline"))[0]?.content ?? "";

  it("states the project facts, the prohibitions and the strictness before any advice", () => {
    const order = [
      "## Project context",
      "## Before you write code",
      "## How this project is organised",
      "## Conventions to mirror",
      "## Dependency rules",
      "## Reference modules",
      "## Project Onboarding",
      "## Clean Code",
    ];
    const positions = order.map((h) => text.indexOf(h));
    expect(positions.every((p) => p >= 0)).toBe(true);
    expect([...positions].sort((a, b) => a - b)).toEqual(positions);
  });

  it("puts the 'do not restructure' prohibition within the first 500 tokens (≈ 2000 characters)", () => {
    expect(text.indexOf("Do not restructure the project")).toBeGreaterThan(0);
    expect(text.indexOf("Do not restructure the project")).toBeLessThan(2000);
  });

  it("names the project's actual directories", () => {
    for (const dir of ["src/controllers", "src/services", "src/repositories"])
      expect(text).toContain(`\`${dir}\``);
  });

  it("states the architecture awareness rule once, not once per skill", () => {
    expect(text.match(/Do not introduce a different structure/g)).toHaveLength(1);
  });

  it("is free of timestamps and tool-specific phrasing", () => {
    expect(text).not.toMatch(/\b\d{4}-\d{2}-\d{2}T/);
    expect(text).not.toMatch(/as Claude|as Codex|as an AI/i);
  });

  it.each(["observe", "minimal", "standard", "strict"] as const)(
    "words the dependency rules for %s strictness",
    (strictness) => {
      const o: CanonicalOutput = existingLayered({
        architecture: { style: "layered", source: "detected", confidence: 0.9, strictness },
      });
      const out = renderAdapter(genericAdapter, o, opts("inline"))[0]?.content ?? "";
      if (strictness === "strict") expect(out).toContain("These are blocking.");
      else expect(out).not.toContain("These are blocking.");
      if (strictness === "observe")
        expect(out).toContain("Learn its conventions before writing code");
    },
  );

  it("describes a migration and a new project differently", () => {
    const migrating =
      renderAdapter(
        genericAdapter,
        existingLayered({
          strategy: "migrate",
          migration: { from: "layered", to: "feature-clean", strategy: "incremental" },
        }),
        opts("inline"),
      )[0]?.content ?? "";
    expect(migrating).toContain("Existing project (migrate)");
    expect(migrating).toContain("Layered → Feature + Clean Architecture (incremental)");
    const fresh =
      renderAdapter(
        genericAdapter,
        existingLayered({ mode: "new", strategy: undefined }),
        opts("inline"),
      )[0]?.content ?? "";
    expect(fresh).toContain("**Mode:** New project");
  });

  it("omits sections it has nothing to say for", () => {
    const o = {
      ...existingLayered({ structure: undefined, conventions: [], dependencyRules: [] }),
      references: [],
    };
    const out = renderAdapter(genericAdapter, o, opts("inline"))[0]?.content ?? "";
    for (const h of [
      "## How this project is organised",
      "## Conventions to mirror",
      "## Dependency rules",
      "## Reference modules",
    ])
      expect(out).not.toContain(h);
  });
});

describe("determinism", () => {
  it.each(Object.values(ADAPTERS).map((a) => [a.id, a] as const))(
    "%s: two renders are identical",
    (_id, adapter) => {
      const a = renderAdapter(adapter, existingLayered(), opts(adapter.defaultMode));
      const b = renderAdapter(adapter, existingLayered(), opts(adapter.defaultMode));
      expect(b).toEqual(a);
    },
  );

  it.each(Object.values(ADAPTERS).map((a) => [a.id, a] as const))(
    "%s: output has LF endings and no trailing whitespace",
    (_id, adapter) => {
      for (const file of renderAdapter(adapter, existingLayered(), opts(adapter.defaultMode))) {
        expect(file.content).not.toContain("\r");
        expect(file.content).not.toMatch(/[ \t]+\n/);
      }
    },
  );

  it("a managed block written from the output is stable across regenerations", () => {
    const [file] = renderAdapter(codexAdapter, existingLayered(), opts("inline"));
    const first = upsertManagedBlock("# Team notes\n", "engineering-skills", file?.content ?? "");
    expect(upsertManagedBlock(first.text, "engineering-skills", file?.content ?? "").status).toBe(
      "unchanged",
    );
  });
});

describe("the adapter contract", () => {
  it("rejects an adapter that writes a path it did not declare", () => {
    const leaky: AiAdapter = {
      id: "leaky",
      displayName: "Leaky",
      defaultMode: "inline",
      outputPaths: () => ["a.md"],
      render: () => [{ path: "somewhere-else.md", content: "x", marker: "full" }],
    };
    expect(() => renderAdapter(leaky, existingLayered(), opts("inline"))).toThrow(
      'undeclared path "somewhere-else.md"',
    );
  });

  it("rejects an adapter that writes the same path twice", () => {
    const dup: AiAdapter = {
      id: "dup",
      displayName: "Dup",
      defaultMode: "inline",
      outputPaths: () => ["a.md"],
      render: () => [
        { path: "a.md", content: "1", marker: "full" },
        { path: "a.md", content: "2", marker: "full" },
      ],
    };
    expect(() => renderAdapter(dup, existingLayered(), opts("inline"))).toThrow("twice");
  });
});
