import { describe, expect, it } from "vitest";
import {
  findManagedBlock,
  inspectGeneratedFile,
  normalize,
  renderGeneratedFile,
  sha256,
  upsertManagedBlock,
} from "./files.js";

const META = { version: "1.2.3", source: ".engineering/config.yaml" };

describe("normalize", () => {
  it("uses LF, strips trailing whitespace and ends with exactly one newline", () => {
    expect(normalize("a  \r\nb\t\r\n\r\n\r\n")).toBe("a\nb\n");
    expect(normalize("x")).toBe("x\n");
  });
});

describe("generated files", () => {
  it("start with the documented header and a content hash", () => {
    const text = renderGeneratedFile({ body: "# Title\n\nBody" }, META);
    expect(text).toMatch(
      /^<!-- GENERATED BY @engineering-skills\/cli v1\.2\.3 — DO NOT EDIT\n {5}Source: \.engineering\/config\.yaml\n {5}Regenerate: eng-skills generate\n {5}Hash: sha256:[0-9a-f]{64} -->\n\n# Title/,
    );
    expect(inspectGeneratedFile(text)).toBe("pristine");
  });

  it("detects a hand edit anywhere in the body", () => {
    const text = renderGeneratedFile({ body: "# Title\n\nBody" }, META);
    expect(inspectGeneratedFile(text.replace("Body", "Edited"))).toBe("edited");
  });

  it("is reproducible: same input, same bytes", () => {
    expect(renderGeneratedFile({ body: "x" }, META)).toBe(renderGeneratedFile({ body: "x" }, META));
  });

  it("covers front matter that must come before the header", () => {
    const text = renderGeneratedFile({ pre: "---\nname: a\n---\n", body: "Body" }, META);
    expect(text.startsWith("---\nname: a\n---\n<!-- GENERATED BY")).toBe(true);
    expect(inspectGeneratedFile(text)).toBe("pristine");
    expect(inspectGeneratedFile(text.replace("name: a", "name: b"))).toBe("edited");
  });

  it("treats a file without the header as not generated", () => {
    expect(inspectGeneratedFile("# My own notes\n")).toBe("not-generated");
  });

  it("ignores CRLF conversion and trailing whitespace added by an editor", () => {
    const text = renderGeneratedFile({ body: "Line one\nLine two" }, META);
    expect(inspectGeneratedFile(text.replace(/\n/g, "\r\n"))).toBe("pristine");
  });
});

describe("managed blocks", () => {
  const block = (content: string) => upsertManagedBlock(undefined, "es", content).text;

  it("creates a file that is just the block", () => {
    const result = upsertManagedBlock(undefined, "es", "Rules\n");
    expect(result.status).toBe("created");
    expect(result.text).toMatch(
      /^<!-- engineering-skills:start id=es hash=sha256:[0-9a-f]{64} -->\nRules\n<!-- engineering-skills:end id=es -->\n$/,
    );
  });

  it("appends to a file the user owns without touching their content", () => {
    const mine = "# My CLAUDE.md\n\nUse tabs.\n";
    const result = upsertManagedBlock(mine, "es", "Rules");
    expect(result.status).toBe("inserted");
    expect(result.text.startsWith(mine)).toBe(true);
    expect(findManagedBlock(result.text, "es")?.content).toBe("Rules\n");
  });

  it("adds a separating blank line when the file does not end with a newline", () => {
    expect(upsertManagedBlock("no newline", "es", "R").text.startsWith("no newline\n\n<!--")).toBe(
      true,
    );
  });

  it("replaces only the block and preserves everything around it byte for byte", () => {
    const before = "top  \r\n\n";
    const after = "\n\nbottom\t\n";
    const first = upsertManagedBlock(before + block("old") + after, "es", "new");
    expect(first.status).toBe("updated");
    expect(first.text.startsWith(before)).toBe(true);
    expect(first.text.endsWith(after)).toBe(true);
    expect(findManagedBlock(first.text, "es")?.content).toBe("new\n");
  });

  it("reports unchanged when the content is identical", () => {
    const text = block("same");
    expect(upsertManagedBlock(text, "es", "same")).toEqual({ text, status: "unchanged" });
  });

  it("refuses to overwrite a block that was edited by hand", () => {
    const edited = block("original").replace("original", "hand edited");
    expect(findManagedBlock(edited, "es")?.edited).toBe(true);
    expect(upsertManagedBlock(edited, "es", "regenerated")).toEqual({
      text: edited,
      status: "conflict",
    });
  });

  it("replaces an edited block in place when forced, keeping the text around it", () => {
    const edited = `before\n${block("original").replace("original", "hand edited")}after\n`;
    const forced = upsertManagedBlock(edited, "es", "regenerated", { force: true });
    expect(forced.status).toBe("updated");
    expect(forced.text.startsWith("before\n")).toBe(true);
    expect(forced.text.endsWith("after\n")).toBe(true);
    expect(findManagedBlock(forced.text, "es")).toMatchObject({
      content: "regenerated\n",
      edited: false,
    });
  });

  it("keeps separate blocks independent", () => {
    const both = upsertManagedBlock(block("one"), "other", "two").text;
    expect(upsertManagedBlock(both, "es", "one!").status).toBe("updated");
    expect(findManagedBlock(upsertManagedBlock(both, "es", "one!").text, "other")?.content).toBe(
      "two\n",
    );
  });

  it("round-trips: the declared hash matches the content", () => {
    const found = findManagedBlock(block("abc"), "es");
    expect(found?.declaredHash).toBe(sha256("abc\n"));
    expect(found?.edited).toBe(false);
  });
});
