import { createHash } from "node:crypto";

/**
 * File discipline for generated output (docs/02-specs/ai-adapter-spec.md §3):
 * every generated file says it is generated and carries a content hash, so a hand edit is
 * detected instead of silently overwritten, and content a user owns is preserved byte for byte.
 */

/** LF endings, no trailing whitespace, exactly one trailing newline. Makes output reproducible. */
export function normalize(text: string): string {
  const lines = text
    .replace(/\r\n?/g, "\n")
    .split("\n")
    .map((l) => l.replace(/[ \t]+$/, ""));
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

export const sha256 = (text: string): string =>
  `sha256:${createHash("sha256").update(text).digest("hex")}`;

// ---------------------------------------------------------------------------------------------
// Whole generated files

export interface HeaderMeta {
  readonly version: string;
  /** Where the content came from, e.g. `.engineering/config.yaml`. */
  readonly source: string;
}

const HEADER_PATTERN = /<!-- GENERATED BY [^]*?Hash: (sha256:[0-9a-f]{64}) -->\n\n/;

/**
 * Assemble a generated file. `pre` (for example YAML front matter a tool requires first) comes
 * before the header. The hash covers `pre` + `body`, i.e. everything except the header itself.
 */
export function renderGeneratedFile(
  parts: { pre?: string; body: string },
  meta: HeaderMeta,
): string {
  const pre = parts.pre === undefined ? "" : normalize(parts.pre);
  const body = normalize(parts.body);
  const header =
    `<!-- GENERATED BY @engineering-skills/cli v${meta.version} — DO NOT EDIT\n` +
    `     Source: ${meta.source}\n` +
    `     Regenerate: eng-skills generate\n` +
    `     Hash: ${sha256(pre + body)} -->\n\n`;
  return pre + header + body;
}

export type GeneratedFileState = "pristine" | "edited" | "not-generated";

/** Has a generated file been hand-edited since it was written? */
export function inspectGeneratedFile(raw: string): GeneratedFileState {
  // An editor may have changed line endings or stripped whitespace; that is not an edit.
  const text = normalize(raw);
  const match = HEADER_PATTERN.exec(text);
  if (!match) return "not-generated";
  const withoutHeader = text.slice(0, match.index) + text.slice(match.index + match[0].length);
  return sha256(normalize(withoutHeader)) === match[1] ? "pristine" : "edited";
}

// ---------------------------------------------------------------------------------------------
// Managed blocks inside a file the user owns (CLAUDE.md, AGENTS.md)

const start = (id: string, hash: string) =>
  `<!-- engineering-skills:start id=${id} hash=${hash} -->`;
const end = (id: string) => `<!-- engineering-skills:end id=${id} -->`;

export interface FoundBlock {
  /** Index of the first character of the start marker. */
  readonly from: number;
  /** Index just past the end marker (and its newline, if any). */
  readonly to: number;
  readonly content: string;
  readonly declaredHash: string;
  readonly edited: boolean;
}

export function findManagedBlock(text: string, id: string): FoundBlock | undefined {
  const open = new RegExp(
    `<!-- engineering-skills:start id=${id} hash=(sha256:[0-9a-f]{64}) -->\\n`,
  );
  const opening = open.exec(text);
  if (!opening) return undefined;
  const closing = end(id);
  const contentStart = opening.index + opening[0].length;
  const closeAt = text.indexOf(closing, contentStart);
  if (closeAt === -1) return undefined;
  const content = text.slice(contentStart, closeAt);
  const to = closeAt + closing.length + (text[closeAt + closing.length] === "\n" ? 1 : 0);
  return {
    from: opening.index,
    to,
    content,
    declaredHash: opening[1] as string,
    edited: sha256(content) !== opening[1],
  };
}

export type BlockStatus = "created" | "inserted" | "updated" | "unchanged" | "conflict";

export interface UpsertResult {
  readonly text: string;
  readonly status: BlockStatus;
}

/**
 * Put `content` in a managed block. Everything outside the block is preserved byte for byte.
 * A block edited by hand is a conflict: the text is returned unchanged for the caller to resolve.
 */
export function upsertManagedBlock(
  existing: string | undefined,
  id: string,
  content: string,
): UpsertResult {
  const body = normalize(content);
  const block = `${start(id, sha256(body))}\n${body}${end(id)}\n`;

  if (existing === undefined || existing === "") return { text: block, status: "created" };

  const found = findManagedBlock(existing, id);
  if (found) {
    if (found.edited) return { text: existing, status: "conflict" };
    if (found.content === body) return { text: existing, status: "unchanged" };
    return {
      text: existing.slice(0, found.from) + block + existing.slice(found.to),
      status: "updated",
    };
  }

  const separator = existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
  return { text: existing + separator + block, status: "inserted" };
}
